### ISSUE TITLE
(SP: 2) [Categories] Add title with description and search input

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-Project/Space2Study-FrontEnd#173]
UserStory: #84
## Description
Add title with description, implement input with searching functionality to search for a category by name
## Design 
![Image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/67462207/d88426b4-97f6-441d-8539-760a49a5570d)
## Acceptance Criteria
- [ ] When a user clicks on the "Show all offers", he/she should be redirected to "find offers" page
- [ ] When a user clicks on the "Search" button or press enter, search should be performed

**Comment by ArtemHolikov** [comment]
It is a spike issue. I will divide it on 2 issues for realize logic of search and realize appearance. I changed amout of story points to 2 and replaced task for realize search logic and assigned it 1 story point. I divided it because we don't have implemented categories page and logic can not be realized.
